import os
import sys

carfac_cpp_path = os.path.join(Dir('../').path, 'cpp')
libsndfile_path = 'C:\Program Files\Mega-Nerd\libsndfile'  # Windows-specific
libsndfile_include_path = os.path.join(libsndfile_path, 'include')

env = Environment(
    CPPPATH=[
        os.environ['EIGEN_PATH'],
        carfac_cpp_path,
        libsndfile_include_path
    ],
    OMP_NUM_THREADS=[os.environ['OMP_NUM_THREADS']],
    LIBPATH=[os.path.join(libsndfile_path, 'lib')],
    LIBS=['libsndfile-1.lib'],
    TARGET_ARCH='x86_64'
)

if not sys.platform == "win32":
    env['CC'] = os.environ['CC']
    env['CXX'] = os.environ['CXX']

env.MergeFlags(['-std=c++11 -O3 -DNDEBUG -fopenmp'])
carfac_sources = [
    os.path.join(carfac_cpp_path, 'binaural_sai.cc'),
    os.path.join(carfac_cpp_path, 'carfac.cc'),
    os.path.join(carfac_cpp_path, 'ear.cc'),
    os.path.join(carfac_cpp_path, 'sai.cc')
]

carfac = env.Library(target='carfac', source=carfac_sources)

carfac_cmd_sources = carfac_sources + ['carfac_cmd.cc']
carfac_cmd = env.Program(target='carfac-cmd',
                         source=carfac_cmd_sources,
                         LINKFLAGS='-std=c++11 -O3 -DNDEBUG -fopenmp')

Default(carfac_cmd)
